name: CI

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.x]
    steps:
      # 1) Check out your repository
      - uses: actions/checkout@v3

      # 2) Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # 3) Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          # Tell Poetry to install into the current env (so we don't end up in another venv)
          poetry config virtualenvs.create false --local

      # 4) Install dependencies
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi --no-root

      # 5) Download punkt
      - name: Download punkt
        run: bash RAGToolBox/Download_punkt.sh

      # 6) Run tests
      - name: Run pytest
        run: bash tests/Run_tests.sh

      # 7) Upload coverage report
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: .coverage
          fail_ci_if_error: true

      # 8) Measure coverage
      - name: Measure test coverage
        run: |
          python utils/check_coverage.py
